### ISSUE TITLE
MIPS/smaller binary

### ISSUE THREAD

**Issue by swedneck** [hyprspace/hyprspace#12]
I've tried compiling hyprspace for MIPS so i can run it on my router, but it turns out that the binary is about 2x as big as all of the storage on my router :D

I'm wondering how feasible it would be to shrink this binary, maybe i'm just missing a bunch of optimization flags for the compiler?
It'd be a shame to not be able to run hyprspace on most routers, since it would be *extremely* useful.

**Comment by alecbcs** [comment]
Interesting! Yeah it's totally possible to make the binary smaller to support routers. I'd take a look at something like [UPX](https://github.com/upx/upx) to compress the binary. If you download the UPX binary for your system, you can run `./upx --brute hyprspace` to compress the hyprspace binary. Doing that I was able to shrink the x86_64 binary from 23MB to 5.3MB. It will increase the time for Hyprspace to launch but it's still probably worth it for your use-case.

**Comment by swedneck** [comment]
Great! Unfortunately that's still half the size of my router's storage, but at least that makes it *possible* to run.

Maybe i'll try plugging a usb drive into the router and see if i can mount that as storage :P

**Comment by alecbcs** [comment]
Cool! Unfortunately the whole libp2p stack is a bit large but definitely let me know if adding the USB works!

**Comment by swedneck** [comment]
Was closing this intentional? Just want to make sure github didn't get overly enthusiastic about "help fix #12" :D
