### ISSUE TITLE
Linux repositories?

### ISSUE THREAD

**Issue by LynHyper** [hyprspace/hyprspace#18]
I realise this might be a lot to ask given how many Linux repositories there are, but could you add Hyprspace within a few of them? Particularly easier (according to what I've heard) repositories to submit to like the AUR and ones like it.

If not, perhaps an install script that streamlines installing and updating the program could be used instead to support as many platforms as possible?

Looking forward to where the project leads.

**Comment by alecbcs** [comment]
Hey @LynHyper! Adding Hyprspace to some Distribution Repositories is definitely on my to do list! I've got experience building and maintaining packages for [Solus](https://getsol.us) but not for many others so I'll have to take a look at learning those other build systems and that might be a slightly longer project. (If anyone else has experience with these other distro packaging systems any help would be greatly appreciated!)

As for what we can work on now, I definitely agree Hyprspace needs a better install script. Maybe something comparable with [rclone's](https://rclone.org/downloads/) or [brew's](https://brew.sh) simple download and install scripts. I'll start taking a look at this over the next week and see if we can't get something put together.

As for updates, Hyprspace actually already has `hyprspace update` which will look for new updates and will actually download and patch it's own binary with an update if one is found! @LynHyper is this what you were thinking of? Or maybe we should work on adding something else? 

Thanks for all your feedback!

Best,
Alec

**Comment by LynHyper** [comment]
Nope, that's pretty much it, I completely forgot about 'hyprspace update'. I think I'll close the issue then.
