### ISSUE TITLE
p2p-*-proxy support?

### ISSUE THREAD

**Issue by LynHyper** [hyprspace/hyprspace#26]
I'm wondering if hyprspace could support connecting to an IPFS node with experimental settings such as p2p-http-proxy or p2p-tcp-proxy? For example:

```
PEER A:

PEER A and PEER B are added to config as normal.
hyprspace init hs0 [hyprspace forwards all non-ipfs queries to 10.1.1.1 (itself)]
```
```
PEER B: [Running an IPFS node and not hyprspace]

Sends request over p2p-*-proxy to PEER-A-ID containing discovery key (or the key in some other form).
```
```
PEER A:

Receives p2p-*-proxy request from PEER B and forwards it to 10.1.1.1.
Connection is established from PEER B to PEER A over p2p-*-proxy's libp2p connection.
```

This might take a fair bit of work, I'm honestly not sure how useful this would be either, let me know what you think.

**Comment by LynHyper** [comment]
On second thoughts, this would create more problems than it solves; it's usecase isn't particularly needed and would directly interfere with hyprspace's existing feature set, I think I'll close this issue.

**Comment by alecbcs** [comment]
Hey @LynHyper apologies I just got back from taking a week off. This would be cool but I think you're right that it might add a lot of complexity to hyprspace. I haven't messed around with the ipfs `p2p-tcp-proxy` functionality but maybe if they're chunking packets similarly to us it could work?
