### ISSUE TITLE
VPN or Overlay Network?

### ISSUE THREAD

**Issue by mrbluecoat** [hyprspace/hyprspace#33]
Hi, cool project! I see you describe it as a VPN but is it more like an Overlay Network (like [Nebula](https://github.com/slackhq/nebula)?) As a VPN I would have assumed you could route all your traffic through it with an external IP showing as the exit node. This looks more like a tool to allow optional connections between systems, right?

**Comment by LynHyper** [comment]
Hyprspace *can* forward all traffic to a node, see the bottom of https://github.com/hyprspace/hyprspace/discussions/3 for how, but, you are correct that without explicit configuration hyprspace does not forward traffic by default. (Not a dev btw)

**Comment by mrbluecoat** [comment]
Thanks @LynHyper ! https://github.com/hyprspace/hyprspace/discussions/3#discussioncomment-1037812 was exactly what I was looking for
