### ISSUE TITLE
cannot ping SBC behind wifi router, from corporate pc

### ISSUE THREAD

**Issue by wfchair** [hyprspace/hyprspace#79]
corporate pc: 
cat hs0.yaml 
interface:
  name: hs0
  id: Qmbdr
  listen_port: 8001
  address: 10.1.1.1/24
  private_key: !!binary |
    Private key here
peers: 
  10.1.1.10:
    id: QmeVT

cat hs0.log 
[+] Creating TUN Device
[+] Creating LibP2P Node
2022/05/05 14:20:07 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
[+] Setting Up Node Discovery via DHT
[+] Network Setup Complete...Waiting on Node Discovery
[+] Connection to 10.1.1.5 Successful. Network Ready.

SBC behind wifi router:
cat hs0.yaml 
interface:
  name: hs0
  id: QmeVT
  listen_port: 8001
  address: 10.1.1.10/24
  private_key: !!binary |
    Private key here
peers: 
  10.1.1.1:
    id: Qmbdr

But, they cannot ping each other. how can I troubleshoot?

by the way, corporate 2 pc's can ping each other by using hyprspace vpn.

**Comment by alecbcs** [comment]
@wfchair it sounds like your company could be blocking outgoing connections to non-standard ports (anything not 80, 443, etc...), I'd take a look at #80 and see if that fixes your issue.

**Comment by alecbcs** [comment]
I'm going to go ahead and close this issue due to a lack of activity. If anyone else runs across this issue feel free to ping me and we can reopen this!
