### ISSUE TITLE
Can not ping when using the phone's wifi or the wifi of university

### ISSUE THREAD

**Issue by Shudeng** [hyprspace/hyprspace#80]
Hello, I have encountered a strange problem.

I have a peer which is a cloud server of tencent and the other peer is my mac/ ubuntu computer.

When my personal computer use the the phone's wifi or the wifi of university, the cloud server and my personal computer cannot ping each other.

However, when I use the expressvpn in the personal computer, the ping operation can be successful.
Can anyone help explain this? Thanks very much.

**Comment by Shudeng** [comment]
I change the port from 8001 to 443, and all peers can ping each other finnaly.

**Comment by Winterhuman** [comment]
The University probably just blocks any non-standard ports (aka most things that aren't HTTP, HTTPS, DNS, etc). I don't think Hyprspace can do much to resolve this itself

**Comment by alecbcs** [comment]
Glad you all figured this out! I agree with @Winterhuman this sounds like your University is blocking access to non standard ports. There really isn't anything we can do within the Hyprspace code base to mitigate this but it might be worth adding a section about this to our docs.
