### ISSUE TITLE
Error I encountered on Windows

### ISSUE THREAD

**Issue by DillFrescott** [hyprspace/hyprspace#83]
2022/07/03 15:07:43 Failed to find the tap device in registry with specified ComponentId 'tap0901' and InterfaceName 'test', TAP driver may be not installed or you may have specified an interface name that doesn't exist

**Comment by DillFrescott** [comment]
I tried installing a tap driver to no avail :( It installed correctly but hyprspace still threw the error.

**Comment by QZAiXH** [comment]
You should modify the tap name to what you need
![image](https://user-images.githubusercontent.com/23068780/177677643-443f29e5-ba39-4b04-8e0e-41040114f22d.png)

**Comment by QZAiXH** [comment]
@DillFrescott You may need to run hyprspace with administrator privileges

**Comment by DillFrescott** [comment]
Ok thank you!

**Comment by alecbcs** [comment]
@DillFrescott were you able to get this working on Windows? If so are you alright if we go ahead and close this issue?

**Comment by DillFrescott** [comment]
Yes I was! Sorry I forgot to mention that in another comment!

**Comment by alecbcs** [comment]
Great! No worries!
