### ISSUE TITLE
config for multiple Peers

### ISSUE THREAD

**Issue by bmullan** [hyprspace/hyprspace#92]
the README file only show 2 peers 

> peers:
  10.1.1.2:
    id: YOUR-OTHER-PEER-ID

but what if each Node is connected to more than 1 peer

Does the above just get expanded to:

> peers:
  10.1.1.2:
      id: your peer2 ID
   10.1.1.3:
      id: your peer3 ID

etc...

**Comment by Winterhuman** [comment]
@bmullan Multiple peers would be configured like:

```
peers:
    10.1.1.2:
        id: PeerID-2
    10.1.1.3:
        id: PeerID-3
    ...
```

**Comment by bmullan** [comment]
Thanks
Thats what I guessed !
